# Generated by Django 3.2.4 on 2021-07-04 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='answer_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
